version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "adrianwedd"
    reviewers:
      - "adrianwedd"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "adrianwedd"
    reviewers:
      - "adrianwedd"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "adrianwedd"
    reviewers:
      - "adrianwedd"
