site_name: AgentIndex
theme: material
plugins:
  - search
  - mkdocstrings
docs_dir: docs
nav:
  - Overview: index.md
  - Methodology: METHODOLOGY.md
  - CLI Usage: cli.md
  - API Reference:
      - agentindex_cli: reference/agentindex_cli.md
