site_name: Agentic Index
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings
docs_dir: docs
nav:
  - Home: index.md
  - Guides:
      - Refresh Pipeline: REFRESH.md
      - CI Audit Report: ci-audit.md
      - Conflict Resolution: CONFLICT_RESOLUTION.md
      - Coverage Baseline: coverage_baseline.md
      - Development Setup: DEVELOPMENT.md
      - Performance Tips: PERFORMANCE.md
      - Metrics Alerts: METRICS_ALERTS.md
  - Methodology: methodology.md
  - CLI Usage: cli.md
  - API Reference:
      - agentic_index_cli: reference/agentic_index_cli.md
      - agentic_index_api: reference/agentic_index_api.md
