site_name: AgentOps
theme: material
plugins:
  - search
  - mkdocstrings
docs_dir: docs
nav:
  - Overview: index.md
  - Methodology: METHODOLOGY.md
  - CLI Usage: cli.md
  - API Reference:
      - agentic_index_cli: reference/agentic_index_cli.md
