site_name: Agentic Index
theme: material
plugins:
  - search
  - mkdocstrings
docs_dir: docs
nav:
  - Home: index.md
  - Guides:
      - Refresh Pipeline: REFRESH.md
      - CI Audit Report: ci-audit.md
      - Conflict Resolution: CONFLICT_RESOLUTION.md
      - Coverage Baseline: coverage_baseline.md
      - Development Setup: DEVELOPMENT.md
  - Methodology: METHODOLOGY.md
  - CLI Usage: cli.md
  - API Reference:
      - agentic_index_cli: reference/agentic_index_cli.md
