name: behind-check
runs:
  using: composite
  steps:
    - shell: bash
      run: echo "Checking branch status…"
    - name: Run branch-behind check
      shell: bash
      run: ./scripts/behind_check.sh
