name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install package
        run: pip install -e .
      - name: Run regression guard
        run: python scripts/regression_check.py
      - name: Run tests with coverage
        run: pytest --cov=agentic_index_cli --cov-report=xml
        env:
          PYTHONHASHSEED: 0
      - name: Check coverage
        run: python scripts/coverage_gate.py coverage.xml
        env:
          PYTHONHASHSEED: 0
      - name: Verify internal links
        run: python scripts/link_integrity.py

  offline-lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install package
        run: pip install -e .
      - name: Install pre-commit
        run: |
          pip install -i https://pypi.org/simple \
                      --trusted-host pypi.org \
                      pre-commit
      - name: Offline network guard
        run: |
          pip install pytest-socket
          pytest --disable-socket -q 2>&1 | tee pytest.log
          python scripts/network_guard.py pytest.log
