name: Docs Build & Link Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install docs dependencies
        run: pip install -r docs/requirements.txt
      - name: Install dependencies
        run: pip install mkdocs-material mkdocstrings[python] sphinx furo
      - name: Build MkDocs site
        run: mkdocs build --strict
      - name: Build Sphinx docs
        run: sphinx-build -b html docs/sphinx docs/sphinx/_build/html -W
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-cache-${{ hashFiles('docs/**/*.md') }}
      - name: Link Check
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          args: >-
            --no-progress
            --exclude "github.com/.*/pull/"
            docs/**/*.md

