name: pip-audit

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266
        with:
          inputs: requirements.txt
          format: sarif
          output: pip-audit.sarif
      - name: Upload pip-audit results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif
