name: pip-audit

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Dependency audit
        uses: pypa/gh-action-pip-audit@v1
        with:
          inputs: requirements.txt
          format: json
          output: pip-audit.json
          summary: true
      - name: Convert audit → SARIF
        run: |
          pipx run pip-audit-sarif pip-audit.json > pip-audit.sarif
      - name: Upload SARIF
        if: ${{ hashFiles('pip-audit.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif
