name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract release notes
        id: changelog
        run: |
          tag="${GITHUB_REF##*/}"
          awk "/## \[${tag#v}\]/,/^## /" CHANGELOG.md > notes.md
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v1
        with:
          body: "${{ steps.changelog.outputs.notes }}"
          draft: false

