name: Rank Repos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install matplotlib
      - name: Run ranker
        run: |
          echo "running ranker" | tee rank.log
          # Placeholder for ranking logic generating repos.json
          python scripts/ranker.py >> rank.log 2>&1
      - name: Archive repos.json
        run: |
          mkdir -p data/history
          if [ -f data/repos.json ]; then
            cp data/repos.json data/history/$(date +%F).json
          fi
      - name: Plot trends
        run: python scripts/plot_trends.py
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update history and trends
      - name: Upload history
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rank-history
          path: data/history/*.json
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rank-logs
          path: rank.log
          if-no-files-found: ignore

