name: Draft Release Notes
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
