name: Update index

on:
  schedule:
    - cron: '30 2 * * 1'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      BRANCH: data-update-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt requests pytest
      - name: Scrape repositories
        run: python scripts/scrape.py --min-stars 50
      - name: Rank repositories
        run: python scripts/rank.py data/repos.json
      - name: Run tests
        run: pytest -q
      - name: Check for updated index
        id: diff
        run: |
          if git diff --quiet --exit-code data/top50.md; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Commit changes
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add data/top50.md data/repos.json
          git commit -m "chore(data): weekly agent index refresh"
          git push --set-upstream origin "$BRANCH"
      - name: Create pull request
        if: steps.diff.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr create --title "chore(data): weekly agent index refresh" --fill --head "$BRANCH" --base main
